---
- name: Basic setup
  hosts: all
  become: true
  gather_facts: true
  vars:
    vm_user: admin
  environment:
    ANSIBLE_FORCE_COLOR: "true"
  vars_files:
    - packages.yml
    - keys.yml
    - token.yml
  tasks:
    - name: Add repositories
      ansible.builtin.deb822_repository:
        name: "{{ item.name }}"
        types: [deb]
        uris: "{{ item.uri }}"
        signed_by: "{{ item.key }}"
        suites: ["{{ item.suite }}"]
        components: ["{{ item.component }}"]
        state: present
        enabled: true
      loop: "{{ key_list }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
        force_apt_get: true

    - name: Login to CR
      community.docker.docker_login:
        registry: "ghcr.io"
        username: "{{ cr_username }}"
        password: "{{ token }}"
        state: present

    - name: Gimme repo
      ansible.builtin.git:
        repo: https://github.com/AET-DevOps25/team-404-name-not-found.git
        dest: /home/{{ vm_user }}/repo
        version: deploy-aet-cluster

    - name: Debug docker-compose config
      environment:
        BRANCH: deploy-aet-cluster
      ansible.builtin.command:
        cmd: docker compose -f /home/{{ vm_user }}/repo/compose.yml config
      register: compose_config
      changed_when: false

    - name: Print docker-compose config
      ansible.builtin.debug:
        var: compose_config.stdout_lines

    - name: Pull the kurva images
      environment:
        BRANCH: deploy-aet-cluster
      ansible.builtin.command:
        cmd: docker compose -f /home/{{ vm_user }}/repo/compose.yml pull
      changed_when: false

    - name: Run app
      environment:
        BRANCH: deploy-aet-cluster
      ansible.builtin.command:
        cmd: docker compose -f /home/{{ vm_user }}/repo/compose.yml up 2>&1 | tee /tmp/compose.log
      changed_when: false

    - name: Show docker logs even on fail
      ansible.builtin.command:
        cmd: cat /tmp/compose.log
      register: compose_log_output
      changed_when: false
      failed_when: false

    - name: Dump compose log
      ansible.builtin.debug:
        var: compose_log_output.stdout_lines
