name: AWS Deployment and Testing

on:
  push:
    branches: [main]

jobs:
  deploy-and-provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write private key to infra/priv.pem
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > infra/priv.pem
          chmod 400 infra/priv.pem

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: Install Ansible
        uses: alex-oleshkevich/setup-ansible@v1.0.1
        with:
          version: "11.6.0"

      - name: Create EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          cd infra
          echo "${{ env.AWS_ACCESS_KEY_ID }}"
          echo "${{ env.AWS_SECRET_ACCESS_KEY }}"
          echo "${{ env.AWS_SESSION_TOKEN }}"
          make deploy

      - name: Provision EC2
        run: |
          cd infra
          echo "cr_username: ${{ github.actor }}" >> token.yml
          echo "token: ${{ secrets.GITHUB_TOKEN }}" >> token.yml
          make ansible
